# Generated by Django 3.0.1 on 2019-12-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
